platform :ios, '7.0'
pod 'AFNetworking', '~> 2.0'
pod 'SSKeychain'
pod 'SVProgressHUD'
pod 'TPKeyboardAvoiding'
pod 'KHGravatar/AFNetworking'
pod 'UrbanAirship-iOS-SDK'
pod 'TestFlightSDK', '~> 2.1.3-noadid-beta'